# python3.9のイメージをダウンロード
FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY ./api /app/api

# socket通信
CMD ["uvicorn", "api.main:app","--uds", "/tmp/uvicorn.sock"]

# tcp通信
# CMD ["uvicorn", "api.main:app", "--port", "8000"]