# python3.9のイメージをダウンロード
FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY ./api /app/api
RUN ls -al

# socket通信
# CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0","--uds", "/tmp/uvicorn.sock", "--reload"]

# tcp通信
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]