version: '3'
services:
  next:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: bash -c "npm run build && npm run start"
    # tty: true
    ports:
      - "3000:3000"
    networks:
      - fastapi_backend_web
networks:
  fastapi_backend_web:
    external: true