# python3.9のイメージをダウンロード
FROM python:3.9-slim-buster
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# 必要なシステムパッケージをインストール
RUN apt-get update && apt-get install -y curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pip install poetry
# 仮想環境をたてない
RUN poetry config virtualenvs.create false

# アプリケーションの依存関係をインストール
COPY pyproject.toml /app/
RUN poetry install

COPY /api /app/app

# uvicornのサーバーを立ち上げる
# ENTRYPOINT ["poetry", "run", "uvicorn", "api.main:app","--port", "9876", "--host", "0.0.0.0", "--reload"]
# socket通信
ENTRYPOINT ["uvicorn", "app.main:app", "--host", "0.0.0.0","--uds", "/tmp/uvicorn.sock", "--reload"]