# python3.9のイメージをダウンロード
FROM python:3.9-slim-buster

RUN apt-get update && \
    groupadd -g 1000 app_user && \
    useradd -m -s /bin/bash -u 1000 -g 1000 app_user

RUN mkdir -p /opt/app && chown -R app_user:app_user /opt/app
WORKDIR /opt/app

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

USER app_user

COPY . /opt/app

# socket通信
CMD ["uvicorn", "main:app","--uds", "/tmp/uvicorn.sock"]

# tcp通信
# CMD ["uvicorn", "api.main:app", "--port", "8000"]